const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const STORE_HISTORY = 'STORE_HISTORY';
const GET_SITETAGS = 'GET_SITETAGS';
const STORE_TAG = 'STORE_TAG';
const REMOVE_TAG = 'REMOVE_TAG';
const UPDATE_ACTIVE = 'UPDATE_ACTIVE';
const UPDATE_SITENAME = 'UPDATE_SITENAME';
const HANDLE_FOOTERTAB = 'HANDLE_FOOTERTAB';
const SHOW_TAG = 'SHOW_TAG';
const SHOW_PROGRESS = 'SHOW_PROGRESS';
const SEARCH_HISTORY = 'SEARCH_HISTORY';
const SEARCH_TAGS = 'SEARCH_TAGS';

const NEW_TAB = 'NEW_TAB';
const SWITCH_TAB = 'SWITCH_TAB';
const REMOVE_TAB = 'REMOVE_TAB';
const STORE_TABHISTORY = 'STORE_TABHISTORY';
const BACK_TABHISTORY = 'BACK_TABHISTORY';
const FORWARD_TABHISTORY = 'FORWARD_TABHISTORY';
const SET_CONTEXT = 'SET_CONTEXT';

export {
    SIGN_IN,
    SIGN_UP,
    STORE_HISTORY,
    GET_SITETAGS,
    STORE_TAG,
    REMOVE_TAG,
    UPDATE_ACTIVE,
    UPDATE_SITENAME,
    HANDLE_FOOTERTAB,
    SHOW_TAG,
    SHOW_PROGRESS,
    SEARCH_HISTORY,
    SEARCH_TAGS,
    NEW_TAB,
    SWITCH_TAB,
    REMOVE_TAB,
    STORE_TABHISTORY,
    BACK_TABHISTORY,
    FORWARD_TABHISTORY,
    SET_CONTEXT
}